services:
  # NGINX
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    links:
      - php-fpm
  # PHP
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html