services:
  # NGINX
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    links:
      - php-fpm
    
  # PHP
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html
    build: 
      context: .
      dockerfile: Dockerfile
  # MYSQL
  mysql:
    image: mysql:8
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_PASSWORD=passwd
      - MYSQL_DATABASE=users
  adminer:
    image: adminer:4
    restart: always
    ports:
      - "8080:8080"
    